// <auto-generated />
using System;
using GG.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GG.Infrastructure.Migrations
{
    [DbContext(typeof(GGDbContext))]
    [Migration("20260107184852_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GG.Domain.Entity.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCategoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GG.Domain.Entity.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Instagram");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Telefone");

                    b.Property<bool>("VIP")
                        .HasColumnType("bit")
                        .HasColumnName("VIP");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("GG.Domain.Entity.Despesa", b =>
                {
                    b.Property<int>("IdDespesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDespesa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDespesa"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descricao");

                    b.Property<bool>("Fixa")
                        .HasColumnType("bit")
                        .HasColumnName("Fixa");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Valor");

                    b.HasKey("IdDespesa");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("GG.Domain.Entity.Fornece", b =>
                {
                    b.Property<int>("IdFornecedor")
                        .HasColumnType("int")
                        .HasColumnName("IdFornecedor");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int")
                        .HasColumnName("IdProduto");

                    b.HasKey("IdFornecedor", "IdProduto");

                    b.HasIndex("IdProduto");

                    b.ToTable("Fornece");
                });

            modelBuilder.Entity("GG.Domain.Entity.Fornecedor", b =>
                {
                    b.Property<int>("IdFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdFornecedor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFornecedor"));

                    b.Property<string>("Contato")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Contato");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.HasKey("IdFornecedor");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("GG.Domain.Entity.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<bool>("Paga")
                        .HasColumnType("bit")
                        .HasColumnName("Paga");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Valor");

                    b.HasKey("IdPedido");

                    b.HasIndex("ClienteIdCliente");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("GG.Domain.Entity.PedidoPrato", b =>
                {
                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("IdPedido");

                    b.Property<int>("IdPrato")
                        .HasColumnType("int")
                        .HasColumnName("IdPrato");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Preco");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.HasKey("IdPedido", "IdPrato");

                    b.HasIndex("IdPrato");

                    b.ToTable("PedidoPrato");
                });

            modelBuilder.Entity("GG.Domain.Entity.Prato", b =>
                {
                    b.Property<int>("IdPrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPrato");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrato"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Preco");

                    b.HasKey("IdPrato");

                    b.ToTable("Pratos");
                });

            modelBuilder.Entity("GG.Domain.Entity.PratoProduto", b =>
                {
                    b.Property<int>("IdPrato")
                        .HasColumnType("int")
                        .HasColumnName("IdPrato");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int")
                        .HasColumnName("IdProduto");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Quantidade");

                    b.HasKey("IdPrato", "IdProduto");

                    b.HasIndex("IdProduto");

                    b.ToTable("PratoProduto");
                });

            modelBuilder.Entity("GG.Domain.Entity.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdProduto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Preco");

                    b.Property<decimal>("QuantidadeAtual")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("QuantidadeAtual");

                    b.Property<string>("UnidadeDeMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UnidadeDeMedida");

                    b.HasKey("IdProduto");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("GG.Domain.Entity.Fornece", b =>
                {
                    b.HasOne("GG.Domain.Entity.Fornecedor", "Fornecedor")
                        .WithMany("Fornecimentos")
                        .HasForeignKey("IdFornecedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GG.Domain.Entity.Produto", "Produto")
                        .WithMany("Fornecimentos")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GG.Domain.Entity.Pedido", b =>
                {
                    b.HasOne("GG.Domain.Entity.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteIdCliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GG.Domain.Entity.PedidoPrato", b =>
                {
                    b.HasOne("GG.Domain.Entity.Pedido", "Pedido")
                        .WithMany("PedidoPratos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GG.Domain.Entity.Prato", "Prato")
                        .WithMany("PedidoPratos")
                        .HasForeignKey("IdPrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Prato");
                });

            modelBuilder.Entity("GG.Domain.Entity.PratoProduto", b =>
                {
                    b.HasOne("GG.Domain.Entity.Prato", "Prato")
                        .WithMany("PratoProdutos")
                        .HasForeignKey("IdPrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GG.Domain.Entity.Produto", "Produto")
                        .WithMany("PratoProdutos")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prato");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GG.Domain.Entity.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("GG.Domain.Entity.Fornecedor", b =>
                {
                    b.Navigation("Fornecimentos");
                });

            modelBuilder.Entity("GG.Domain.Entity.Pedido", b =>
                {
                    b.Navigation("PedidoPratos");
                });

            modelBuilder.Entity("GG.Domain.Entity.Prato", b =>
                {
                    b.Navigation("PedidoPratos");

                    b.Navigation("PratoProdutos");
                });

            modelBuilder.Entity("GG.Domain.Entity.Produto", b =>
                {
                    b.Navigation("Fornecimentos");

                    b.Navigation("PratoProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
